### ISSUE TITLE
Fix quick tap bug for hold buttons

### ISSUE THREAD

**Issue by triznakj** [rockwotj/noHuddle#7]
For the tap and hold  buttons, fix the bug that causes a quick tap and release to toggle the play/pause. Instead, cancel any request for a tap and release that occurs in a small amount of time.

**Comment by rockwotj** [comment]
@triznakj is this fixed?

**Comment by triznakj** [comment]
Working on it tonight. For some reason the communicator stopped working so I haven't been able to see for sure.

**Comment by rockwotj** [comment]
Weird. No rush on working on stuff, just wanted to see. If you cant get fixes on your end, I can look at finding some hacks on my end
